version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/rag-backend1:latest
    ports:
      - "5000:5000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./data:/app/data  # Persist PDF files
      - ./faiss_index:/app/faiss_index  # Persist FAISS index
    command: ["sh", "-c", "python3 main.py && uvicorn main:app --host 0.0.0.0 --port 5000"]
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/rag-frontend1:latest
    ports:
      - "8501:8501"
    depends_on:
      - backend
    restart: always





